version: '2'
services:
    db1host:
        image: "postgres:9.4"
        ports:
          - "5432:5432"
        environment:
          POSTGRES_PASSWORD: postgres
        # volumes:
    web:
        image: hcoa/todoapi
        #build: .
        ports:
          - "4000:4000"
        environment:
          MIX_ENV: prod
          DB_USER: postgres
          DB_PASS: postgres
